kind: Deployment
apiVersion: apps/v1
metadata:
  name: general-electric-deployment
  labels:
    app: general-electric
spec:
  replicas: 1
  selector:
    matchLabels:
      app: general-electric
  template:
    metadata:
      labels:
        app: general-electric
    spec:
      containers:
        - name: console-panel
          image: sergiicherepanov/general-electric
          ports:
            - containerPort: 8080
